apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidapp01
spec:
  selector:
    matchLabels:
      app: sidapp01
  template:
    metadata:
      labels:
        app: sidapp01
    spec:
      containers:
      - name: sidapp01
        image: acrlab01.azurecr.io/sidapp01:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

